import { Inter } from "next/font/google";
import "@/app/globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ManageMyAccountPage from "@/components/ManageMyAccountPage";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Digital UI Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body
        className={cn("relative h-full font-sans antialiased", inter.className)}
      >
        <Navbar />
        <div className="flex">
          <ManageMyAccountPage />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
